### ISSUE TITLE
500 server error

### ISSUE THREAD

**Issue by commagray** [ZerataX/matrix-registration#2]
After registration Python says that in output:
```
2018-06-09 20:51:30,888 - flask.app - ERROR - Exception on /register [POST]
Traceback (most recent call last):
  File "/home/commagray/Build/matrix-registration/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/commagray/Build/matrix-registration/lib/python3.6/site-packages/flask/app.py", line 1815, in full_disp
atch_request
    rv = self.handle_user_exception(e)
  File "/home/commagray/Build/matrix-registration/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_us
er_exception
    reraise(exc_type, exc_value, tb)
  File "/home/commagray/Build/matrix-registration/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/commagray/Build/matrix-registration/lib/python3.6/site-packages/flask/app.py", line 1813, in full_disp
atch_request
    rv = self.dispatch_request()
  File "/home/commagray/Build/matrix-registration/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_
request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/commagray/Build/matrix-registration/matrix_registration/api.py", line 175, in register
    device_id=account_data['device_id'],
KeyError: 'device_id'
2018-06-09 20:51:30,906 - werkzeug - INFO - 127.0.0.1 - - [09/Jun/2018 20:51:30] "POST /register HTTP/1.0" 500 -
```
And browser redirects to /register and shows 500 error page, but registration works well.

So how can I change that confusing page by something else?

**Comment by ZerataX** [comment]
apparently the homeserver doesn't actually return a device_id on registration, so simply removing that line should have fixed it.

currently the response page after registering should be just a json, but I'll try to provider a more user-friendly example page soon.

you maybe also want to take a look at how the demo page is setup:
https://github.com/ZerataX/matrix-registration/blob/gh-pages/demo.js#L69
