### ISSUE TITLE
JSON decode error

### ISSUE THREAD

**Issue by boogewooge** [ZerataX/matrix-registration#49]
After the latest update, when trying to register I'm getting

```
Dec 17 22:24:46 okcool python3[1812240]: [2020-12-17 22:24:46,039] ERROR in app: Exception on /register [POST]
Dec 17 22:24:46 okcool python3[1812240]: Traceback (most recent call last):
Dec 17 22:24:46 okcool python3[1812240]:   File "/home/matrix-registration/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
Dec 17 22:24:46 okcool python3[1812240]:     response = self.full_dispatch_request()
Dec 17 22:24:46 okcool python3[1812240]:   File "/home/matrix-registration/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
Dec 17 22:24:46 okcool python3[1812240]:     rv = self.handle_user_exception(e)
Dec 17 22:24:46 okcool python3[1812240]:   File "/home/matrix-registration/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
Dec 17 22:24:46 okcool python3[1812240]:     reraise(exc_type, exc_value, tb)
Dec 17 22:24:46 okcool python3[1812240]:   File "/home/matrix-registration/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
Dec 17 22:24:46 okcool python3[1812240]:     raise value
Dec 17 22:24:46 okcool python3[1812240]:   File "/home/matrix-registration/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
Dec 17 22:24:46 okcool python3[1812240]:     rv = self.dispatch_request()
Dec 17 22:24:46 okcool python3[1812240]:   File "/home/matrix-registration/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
Dec 17 22:24:46 okcool python3[1812240]:     return self.view_functions[rule.endpoint](**req.view_args)
Dec 17 22:24:46 okcool python3[1812240]:   File "/home/matrix-registration/env/lib/python3.8/site-packages/matrix_registration/api.py", line 177, in register
Dec 17 22:24:46 okcool python3[1812240]:     error = resp.json()
Dec 17 22:24:46 okcool python3[1812240]:   File "/home/matrix-registration/env/lib/python3.8/site-packages/requests/models.py", line 900, in json
Dec 17 22:24:46 okcool python3[1812240]:     return complexjson.loads(self.text, **kwargs)
Dec 17 22:24:46 okcool python3[1812240]:   File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
Dec 17 22:24:46 okcool python3[1812240]:     return _default_decoder.decode(s)
Dec 17 22:24:46 okcool python3[1812240]:   File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
Dec 17 22:24:46 okcool python3[1812240]:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
Dec 17 22:24:46 okcool python3[1812240]:   File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
Dec 17 22:24:46 okcool python3[1812240]:     raise JSONDecodeError("Expecting value", s, err.value) from None
Dec 17 22:24:46 okcool python3[1812240]: json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

This happens both when `curl`ing locally and with the web interface.

OS: Ubuntu 20.04

**Comment by ZerataX** [comment]
Hmm I can't reproduce this.
I created a ubuntu 20.04 vm
did `pip install matrix_registration`
which should be v0.8.0

and I could easily create a new test account.
maybe check the developer console in your browser?

the homeserver endpoint has changed to `example.tld/_synapse/admin/v1/register` instead of `example.tld/_matrix/client/r0/admin/register`
so maybe a reverse proxy setup doesn't proxy this particular path?

**Comment by boogewooge** [comment]
Oh, yeah, you were right! I missed that, the new endpoint was in fact not proxied yet!

After fixing this, it works fine. Thanks for the tip and sorry for the trouble. =)
