### ISSUE TITLE
AttributeError: 'Config' object has no attribute 'logging'

### ISSUE THREAD

**Issue by axelsimon** [ZerataX/matrix-registration#50]
**Describe the bug**
matrix-registration fails to start and throws a `AttributeError: 'Config' object has no attribute 'logging'` error.

**To Reproduce**
1. install using pip3, as per the README
2. run with `sudo -u synapse matrix-registration --config-path /etc/matrix-synapse/homeserver.yaml serve`
3. matrix-registration exits in error

**Expected behaviour**
not exiting in error :)

**Screenshots**
```
sudo -u synapse matrix-registration --config-path /etc/matrix-synapse/homeserver.yaml serve
Traceback (most recent call last):
  File "/usr/local/bin/matrix-registration", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1256, in invoke
    Command.invoke(self, ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/matrix_registration/app.py", line 35, in cli
    logging.config.dictConfig(config.config.logging)
AttributeError: 'Config' object has no attribute 'logging'
```

**System:**
 - OS: Debian Bullseye
 - python version:
   - python --version Python 2.7.18
   - python34 --version Python 3.9.1
 - matrix registration version: matrix-registration-0.8.0

**Additional context**
Running this as the matrix-synapse user, not sure if it matters.

**Comment by ZerataX** [comment]
the config needed is different to the synapse config.

here is a sample file: https://github.com/ZerataX/matrix-registration/blob/master/config.sample.yaml

**Comment by axelsimon** [comment]
Ah, ok. Thanks.
The README needs an update then.
I'll try to do that.
